kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["namespaces", "rcs", "svcs", "pods", "podpresets", "cms", "egressnetworkpolicies", "rolebindingrestrictions", "limitranges", "resourcequotas", "pvcs", "pvcs_attachment", "ingress", "replicasets", "poddisruptionbudget", "daemonset"]
  verbs: ["get", "list"]
