kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-reader
rules:
- apiGroups: [""]
  resources:
{{ if .Values.backupSecrets }}
  - secrets
{{ end }}
  - rolebindings
  verbs: ["get", "watch", "list"]
