{{ if .Values.backupEphemeral }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backupCapacity | quote }}
{{ end }}
